defmodule KairosWeb.Component do
  @moduledoc """
  Base module for Salad UI components.
  All components generated by `mix salad.add` use this module.
  """
  defmacro __using__(_opts) do
    quote do
      use SaladUI, :component
    end
  end
end
